name: Upload Website

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm ci
    - run: DISABLE_ESLINT_PLUGIN=true CI=false npm run build
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: www.freeinternationalartists.it
        AWS_ACCESS_KEY_ID: AKIA5O6V3HG6DUT3PW4J
        AWS_SECRET_ACCESS_KEY: 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
        AWS_REGION: 'eu-south-1'   # optional: defaults to us-east-1
        SOURCE_DIR: 'build'      # optional: defaults to entire repository
